// react-stencil/src/App.js
import './App.css';

function App() {
  return (
    <div className="App">
      <my-component
        first="Stencil"
        middle="Library"
        last="Don't call me a framework' JS"
        buttonClicked={(e) => {
          console.log(e,'e');
        }}
      ></my-component>
    </div>
  );
}

export default App;

// angular-stencil/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-stencil';

  @HostListener('buttonClicked',['$event'])
  onMyComponentButtonClick(event: any) {
    console.log(event, 'clicked');
  }
}

<my-component
    first="Stencil"
    middle="Library"
    last="Don't call me a framework' JS"
  ></my-component>
